Repository brazil-data-cube/oauth, pull requests merged in 2019-08, with the labels that each got.

#20 Improve documentation to setup OAuth
  .dockerignore
  .env
  .gitignore
  README.md
  docker-compose.yml
  docs/source/running.rst
  examples/README.md
  examples/oauth-docker-registry/README.md
  examples/oauth-docker-registry/docker-compose.yml
Labels: documentation

#22 fix jwt decode in change-password
  bdc_oauth/auth/decorators.py
Labels: bug

#23 Duplicate authorized customer
  bdc_oauth/auth/business.py
  bdc_oauth/users/serializers.py
Labels: bug

#24 Improve user creation as admin and token request
  bdc_oauth/auth/controller.py
  bdc_oauth/users/business.py
  bdc_oauth/users/controller.py
  bdc_oauth/users/parsers.py
Labels: bug, enhancement
